basePath: /api/v1
definitions:
  models.PhoneNumber:
    properties:
      created_at:
        type: string
      id:
        type: integer
      phone:
        description: 手机号
        type: string
      status:
        description: 手机号状态 0-未售 1-已售
        type: integer
      updated_at:
        type: string
    type: object
  request.GetOpenID:
    properties:
      code:
        type: string
    type: object
  request.GetReservationRecord:
    properties:
      phone:
        description: 手机号 加密
        type: string
      verify_code:
        description: 验证码
        type: string
    type: object
  request.ReservationPhone:
    properties:
      contact_phone:
        description: 加密
        type: string
      identify_card:
        description: 加密
        type: string
      open_id:
        type: string
      real_name:
        type: string
      reservation_phone_id:
        type: integer
      salesman_id:
        type: integer
      school:
        type: string
    type: object
  request.SearchPhone:
    properties:
      suffix:
        type: string
    type: object
  request.ShotMessageCode:
    properties:
      number:
        description: 手机号
        type: string
    required:
    - number
    type: object
  response.DTO:
    properties:
      code:
        description: 响应代码
        type: integer
      data:
        description: 相应数据
      msg:
        description: 响应消息
        type: string
    type: object
  response.GetOpenID:
    properties:
      open_id:
        type: string
    type: object
  response.GetReservationRecord:
    properties:
      contact_phone:
        description: 联系电话 加密
        type: string
      created_at:
        description: 订单时间
        type: string
      identify_card:
        description: 身份证 加密
        type: string
      real_name:
        description: 真实名字
        type: string
      reservation_phone:
        description: 预定电话 加密
        type: string
      salesman_id:
        description: 推销员id
        type: integer
      salesman_name:
        description: 推销员名字
        type: string
      salesman_phone:
        description: 推销员电话 加密
        type: string
      school:
        description: 预约学校
        type: string
      status:
        description: 订单状态 0-未支付 1-支付成功 2-错误
        type: integer
    type: object
  response.GetsRandomPhoneNumbers:
    properties:
      numbers:
        items:
          $ref: '#/definitions/models.PhoneNumber'
        type: array
    type: object
  response.ReservationPhone:
    properties:
      appId:
        type: string
      nonceStr:
        type: string
      package:
        type: string
      paySign:
        type: string
      prepay_id:
        type: string
      signType:
        type: string
      timeStamp:
        type: string
    type: object
  response.SearchPhone:
    properties:
      number:
        items:
          $ref: '#/definitions/models.PhoneNumber'
        type: array
    type: object
info:
  contact: {}
  title: Swagger API
  version: "1.1"
paths:
  /base/captchaPhone:
    post:
      consumes:
      - application/json
      parameters:
      - description: 传入参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ShotMessageCode'
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/response.DTO'
      summary: 获取手机验证码
      tags:
      - 验证
  /reservation/getRandomPhoneNumbers:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/response.GetsRandomPhoneNumbers'
      summary: 获取随机手机号
      tags:
      - 预约前台
  /reservation/getReservationRecord:
    post:
      consumes:
      - application/json
      parameters:
      - description: 参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetReservationRecord'
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            $ref: '#/definitions/response.GetReservationRecord'
      summary: 获取预约记录
      tags:
      - 预约前台
  /reservation/reservationPhone:
    post:
      consumes:
      - application/json
      parameters:
      - description: 参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ReservationPhone'
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            $ref: '#/definitions/response.ReservationPhone'
      summary: 预约手机号
      tags:
      - 预约前台
  /reservation/searchPhone:
    post:
      consumes:
      - application/json
      parameters:
      - description: 参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.SearchPhone'
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/response.SearchPhone'
      summary: 模糊查找手机号
      tags:
      - 预约前台
  /wechat/getOpenID:
    post:
      consumes:
      - application/json
      parameters:
      - description: 参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.GetOpenID'
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            $ref: '#/definitions/response.GetOpenID'
      summary: 获取微信openid
      tags:
      - 微信
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
